version: '3.8'

services:
  web:
    build: .
    command: gunicorn RouteFinder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - DEBUG=True # Set to False in production
      - ALLOWED_HOSTS=*
